### ISSUE TITLE
Feature request, LN node creation: allow specifying existing bitcoind node vs. make new one

### ISSUE THREAD

**Issue by lockhartheavyindustries** [PierreRochard/node-launcher#1]
For quick spinup of a new LN node, if there's already an existing bitcoind node available, prompt the user to provide name + RPC credentials for it. (No sense having multiple bitcoin nodes running if you just want to launch a new LN node.)

**Comment by PierreRochard** [comment]
If you don't mind @lockhartheavyindustries I'm assigning this to myself because I think an automated approach is possible, where it searches for a bitcoind process and then attempts to automatically communicate with it

**Comment by lockhartheavyindustries** [comment]
Absolutely! If you can find a way to auto-detect-attach that'd be super slick.

**Comment by otech47** [comment]
+1 on this, first thing I tried to do before finding this issue

May be able to help out a bit as well if needed

**Comment by otech47** [comment]
@PierreRochard I am seeing two distinct user experiences:

1. When the user opens node-launcher and already has a Bitcoin Core node running, the node-launcher UI should indicate that the node has been detected and does not present the user with the option to launch another Node
2. When the user opens node-launcher, does not have a node running but has Bitcoin Core installed already, the node-launcher UI should guide the user to specify their `bitcoin.conf` file / data directory and launch bitcoind directly from the node-launcher UI

It seems the first would necessarily follow after the second has been achieved and the `BitcoinConfiguration` init definition already has a [`configuration_path` parameter](https://github.com/PierreRochard/node-launcher/blob/master/node_launcher/configuration/bitcoin_configuration.py#L13) (that is left blank by default, but used in some tests) that seems pretty close to functional if we were to grab the value from `widget.data_directory_group_box.datadir` and use it to create and set a new `BitcoinConfiguration` to `bitcoin_mainnet_conf`. Not sure what implications this would have elsewhere though...

If you're on top of this already I'd be happy to review a PR when it's ready.

**Comment by PierreRochard** [comment]
Thanks for looking into it @otech47! I've added the auto-detect code in this pull request: https://github.com/PierreRochard/node-launcher/pull/31 
Sorry I should've broken it up, I was pessimistic about anyone reviewing it!
