### ISSUE TITLE
Lightning Node running perfectly...except lnd.conf file is empty.

### ISSUE THREAD

**Issue by rbuckhoy** [PierreRochard/node-launcher#106]
Lightning Node running perfectly...except lnd.conf file is empty. This makes it impossible to run RTL which relies on this file. Im runnning on Windows. .conf file is on this path:

C:\Users\<ME>\AppData\Local\Lnd\lnd.conf

Contents:

# Auto-Generated Configuration File

# Node Launcher version 5.3.0

**Comment by PierreRochard** [comment]
Thanks, I'll get that fixed in the next version!

**Comment by rbuckhoy** [comment]
Updating RTL now. I think it creates its own .conf.

**Comment by rbuckhoy** [comment]
With the new RTL release that has its own configuration file testnet and mainnet is a full go. Closing
