### ISSUE TITLE
Handshake failed with fatal error SSL_Error

### ISSUE THREAD

**Issue by ArbenKarb** [PierreRochard/node-launcher#109]
Hi I did the following:

- ran node-launcher
- bitcoin blockchain fully synced
- no changes made to config 
- launch LND -> Handshake failed

Edit: src/core/tsi/ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.

LND buttons (Unlock / Create / Recover) remain disabled

**Comment by PierreRochard** [comment]
Close LND
Click on the Show Macaroons button, keep going up the parent directories until you find the Lnd directory. If Show Macaroons is greyed out go to %localappdata%/Lnd on Windows or ~/Library/Application Support/Lnd on macOS
Delete the tls.cert and tls.key files

Fix will be in next version!
