### ISSUE TITLE
Stuck on "Unlock" when forgot password

### ISSUE THREAD

**Issue by jasonedison** [PierreRochard/node-launcher#110]
Having forgotten my lnd wallet seed passphrase--I still have the seed, and luckily no funds in the wallet ;) -- I'm stuck on the screen with only "unlock" as an option. There doesn't appear to be a way to `create` or `recover` in this state:

<img width="471" alt="screenshot 2019-01-06 11 20 35" src="https://user-images.githubusercontent.com/46249890/50740563-2e905e00-11a5-11e9-8713-3a7b41dea0e5.png">

**Comment by PierreRochard** [comment]
Open up `/Applications/Utilities/Keychain Access`

Click on `All Items` at the bottom left

Search for `lnd_mainnet_wallet_password`

Boom, you found your password! 

:)

Let me know if it doesn't work and I'll help with recovery
