### ISSUE TITLE
macos 10.13

### ISSUE THREAD

**Issue by markusbingert** [PierreRochard/node-launcher#132]

**Comment by PierreRochard** [comment]
Hi @markusbingert were you able to get it working?

**Comment by markusbingert** [comment]
No, i‘m just making a software-update on my Mac but I’m not sure why the button „create“ is gray, did you see something strange on my picture?

Thank for you’re help

**Comment by PierreRochard** [comment]
It should be gray if you have already created a LND Wallet or LND is not running yet

**Comment by markusbingert** [comment]
If you look at the pictures i send you the Bitcoin FullNodes are running, i pressed on the Launch LND and in the Terminal everything looks fine.
Still the 3 Buttons are not active „Unlock“ „Create“ „Recover“

Is there anything strange on the picture?

> Am 26.01.2019 um 15:42 schrieb Pierre Rochard <notifications@github.com>:
> ould be gray if you have already created a LND Wallet or LND is not running yet
