### ISSUE TITLE
Zap could no longer open my wallet

### ISSUE THREAD

**Issue by Scron4** [PierreRochard/node-launcher#139]
Running WIN10, 

It also messed up my Zap desktop, Zap could no longer open my wallet. 

Reverted to 5.3 and everything is fine.

**Comment by PierreRochard** [comment]
> Node Launcher 5.4 remembers LND password after first typing it

Yes, that allows the node launcher to automatically unlock the wallet

> Zap could no longer open my wallet

Hmm I didn't have that problem when testing on Windows 7, I'll try it out on Windows 10. Might be a Zap problem.

**Comment by arkaananda** [comment]
is this the same issue:
<img width="422" alt="screenshot 2019-01-29 at 13 00 24" src="https://user-images.githubusercontent.com/29012185/51907006-e3452600-23c5-11e9-976b-559344fc9842.png">
 
when Zap open up it says cannot connect or some such sense and then it seems as if the wallet is completely new and my funds and channels don't appear.

**Comment by Scron4** [comment]
That is the same issue I had exactly.

**Comment by bitstep-btc** [comment]
I do have the same issue also on win10. 
![screenshot 2019-01-29 at 15 34 47](https://user-images.githubusercontent.com/39833203/51915490-86ed0100-23db-11e9-8ac9-260864f87ffa.png)

**Comment by arkaananda** [comment]
I forgot to leave my operating system. 
macOS 10.14.2

**Comment by arkaananda** [comment]
That fixed it for me.  Thanks!
