### ISSUE TITLE
Failure to Launch on MacOS 10.14.2

### ISSUE THREAD

**Issue by EvilGeniusTechnologies** [PierreRochard/node-launcher#141]
**$** ls
Node.Launcher.app
**$** Node.Launcher.app
-bash: Node.Launcher.app: command not found

Also of interest:  When I do a **Get Info** on the application icon, it shows version 0.0.0.   Just FYI.

**Comment by PierreRochard** [comment]
The command line sees Node.Launcher.app as a directory, not an executable

Try this out: https://medium.com/@pierre_rochard/debugging-the-node-launcher-on-macos-b7db0f732ba3

Will reopen if that doesn't fix it

**Comment by EvilGeniusTechnologies** [comment]
Fixed!  Thanks.  :)
