### ISSUE TITLE
New Version Node Launcher ERROR MAC OS

### ISSUE THREAD

**Issue by jordimorris** [PierreRochard/node-launcher#143]
![image](https://user-images.githubusercontent.com/10827671/51909284-8b5ded80-23cc-11e9-9476-3b688519058a.png)

**Comment by PierreRochard** [comment]
This may be a known bug with Zap Desktop: it has to be opened before you click the button in the Node Launcher

I've updated the instructions here https://medium.com/lightning-power-users/easy-lightning-with-node-launcher-zap-488133edfbd

Please let me know if it's still not working!
