### ISSUE TITLE
Provide instructions for changing default datadir

### ISSUE THREAD

**Issue by PierreRochard** [PierreRochard/node-launcher#15]
On Windows: 
Open the text file at %appdata%/Bitcoin/bitcoin.conf

Add or modify the datadir=D:\Bitcoin or whatever

Let me know if that’s confusing / doesn’t work, happy to help!

**Comment by tooraj-enayati** [comment]
Alternatively  just use the Bitcoin Core client and access the configuration file via the menu: Settings > Options... > Wallet > Open Configuration File

**Comment by PierreRochard** [comment]
Thanks @tooraj-enayati! I've added the ability to set the `datadir` straight from the Node Launcher

![image](https://user-images.githubusercontent.com/6299681/49296253-b936bc80-f485-11e8-9401-b7e5da0517cd.png)
