### ISSUE TITLE
Allow lnd.conf button

### ISSUE THREAD

**Issue by leon-do** [PierreRochard/node-launcher#150]
Have you considered adding a lnd.conf button to node-launcher?

bitcoin-qt has a config button which makes it simple to access 😄 

![](https://i.imgur.com/zzjPc3G.png)

**Comment by PierreRochard** [comment]
Yes! Click on Advanced...

![image](https://user-images.githubusercontent.com/6299681/52097209-f7d91800-2597-11e9-92ba-ea4ef0fc70b3.png)
