### ISSUE TITLE
"Could not open requirements file"

### ISSUE THREAD

**Issue by coinsmith** [PierreRochard/node-launcher#2]
After this command in a venv

python -m pip install --index-url=http://download.qt.io/snapshots/ci/pyside/5.11/latest pyside2 --trusted-host download.qt.io

I can't find the 'requirements.txt' for the command 'pip install -r requirements.txt'

Thanks.

Edit, on Ubuntu 16.04

**Comment by PierreRochard** [comment]
Ah sorry, I should've mentioned `git clone https://github.com/PierreRochard/node-launcher && cd node-launcher`, adding that now thank you @coinsmith ! Let me know if it's the right solution.

Btw this will definitely have bugs in linux because I haven't tested it there yet at all, keep me posted!

**Comment by PierreRochard** [comment]
Ah sorry, I should've mentioned `git clone https://github.com/PierreRochard/node-launcher && cd node-launcher`, adding that now thank you @coinsmith ! Let me know if it's the right solution.

Btw this will definitely have bugs in linux because I haven't tested it there yet at all, keep me posted!

**Comment by coinsmith** [comment]
Ah, good to know it isn't me goofing up because of a lack of python knowledge. 

The 'pytest tests' gives a bunch of syntax errors, I've put them in a pastebin file.
https://pastebin.com/SvQ8dVtk

**Comment by PierreRochard** [comment]
Ah yeah you're using python 3.5, I'll update the readme to be 3.6+ as f-strings don't work in 3.5

**Comment by PierreRochard** [comment]
Do you have a way of upgrading to 3.6? might no be possible on ubuntu

**Comment by coinsmith** [comment]
Ah, I think so, I've installed Anaconda once on an old offline laptop. Will try that on the other machine & keep you posted.

**Comment by coinsmith** [comment]
Ah, I think so, I've installed Anaconda once on an old offline laptop. Will try that on the other machine & keep you posted.

**Comment by coinsmith** [comment]
Results with python3.7
a few failed tests and a segmentation fault upon running 'python3.7 run.py'

https://pastebin.com/MyHuRXiL

**Comment by PierreRochard** [comment]
I don't use Linux on desktop/laptop so it is not currently supported, hopefully someone comes a long with a pull request to fix that! I'd be happy to merge it in
