### ISSUE TITLE
Can't launch on MacOS (10.14.1)

### ISSUE THREAD

**Issue by Jonbros01** [PierreRochard/node-launcher#40]
The Node Launcher app dosent seems to work on the latest MacOs.  If I open the app close immediately, no GUI is showing, no error message.

**Comment by PierreRochard** [comment]
You’re not alone! Got a similar bug report via twitter DM. I’ll have a solution out asap

**Comment by HarrieNatnek** [comment]
MacOs versions;
10.10.5
10.13.6
both not working, will wait for new release

**Comment by PierreRochard** [comment]
I think this is two separate bugs.

The first bug gives this output: 

<img width="585" alt="error 0" src="https://user-images.githubusercontent.com/6299681/49699813-dc5b1d80-fba3-11e8-8498-54ee6667a45c.png">

Google led me to this issue: https://github.com/pyinstaller/pyinstaller/issues/3418

Which has this solution: https://pythonhosted.org/PyInstaller/usage.html#making-mac-os-x-apps-forward-compatible

> **Making Mac OS X apps Forward-Compatible**

> In Mac OS X, components from one version of the OS are usually compatible with later versions, but they may not work with earlier versions.

> The only way to be certain your app supports an older version of Mac OS X is to run PyInstaller in the oldest version of the OS you need to support.

> For example, to be sure of compatibility with “Snow Leopard” (10.6) and later versions, you should execute PyInstaller in that environment. You would create a copy of Mac OS X 10.6, typically in a virtual machine. In it, install the desired level of Python (the default Python in Snow Leopard was 2.6, which PyInstaller no longer supports), and install PyInstaller, your source, and all its dependencies. Then build your app in that environment. It should be compatible with later versions of Mac OS X.

The oldest macOS version I have is 10.12.6, so I will be sure to build on that going forward. I looked into installing 10.10 in a virtual machine but the ISO images are not available from Apple 👎

**Comment by PierreRochard** [comment]
The third bug that I think was affecting everyone is that the tls.cert file was expected, but it only gets created after LND has been run. Fixing it for the next release

<img width="585" alt="error 2" src="https://user-images.githubusercontent.com/6299681/49702713-708bab80-fbc9-11e8-9000-96e50674c7e1.png">

**Comment by PierreRochard** [comment]
Please let me know if the latest release works for you @Jonbros01 and @HarrieNatnek ! Cheers
