### ISSUE TITLE
Make an error dialog for BTC node already running without ZMQ

### ISSUE THREAD

**Issue by benthecarman** [PierreRochard/node-launcher#42]

**Comment by PierreRochard** [comment]
So it opens if Bitcoin Core is not already running?

**Comment by benthecarman** [comment]
![70775e15076e41847a5aa898ee90b463](https://user-images.githubusercontent.com/15256660/49558857-2d33f300-f8d2-11e8-8355-169d3399c420.png)
This is my console as it closes

**Comment by benthecarman** [comment]
The problem might be stemming from me having my bitcoin core datadir not as the default

**Comment by PierreRochard** [comment]
The error about the zmq ports is buried in there, I’ll make a proper error dialog. Thanks for reporting!

**Comment by PierreRochard** [comment]
Custom datadir should work perfectly
