### ISSUE TITLE
Guidance on opening ZMQ ports

### ISSUE THREAD

**Issue by otech47** [PierreRochard/node-launcher#71]
![screenshot_25](https://user-images.githubusercontent.com/4914611/50198466-cbd04300-0319-11e9-84dd-610ee7f736dc.png)

I understand this may just be an unimplemented feature, but this is what led me to the other error in #70 

Can I simply change some config on Bitcoin Core and get past this? Or should I try to open directly from Node Launcher every time?

**Comment by PierreRochard** [comment]
I actually just merged in a fix for this, so you’ll only have to use the node launcher once and it’ll write the zmq config to the file

**Comment by PierreRochard** [comment]
To answer the actual question, add 

zmqpubrawblock=tcp://127.0.0.1:18501
zmqpubrawtx=tcp://127.0.0.1:18502

To your bitcoin.conf file in %appdata%/Bitcoin

**Comment by otech47** [comment]
Awesome thanks 👌
