### ISSUE TITLE
Handle TLS problems better

### ISSUE THREAD

**Issue by jchello** [PierreRochard/node-launcher#72]
Currently unable to create a wallet due to what appears to be a connection issue of some kind. I am able to progress up to the point of 'launch LND' at which point most options are greyed out. Any guidance for a relative newbie to resolve this? Thanks!
![screen shot 2018-12-19 at 2 49 56 pm](https://user-images.githubusercontent.com/9296962/50247700-42af1f80-039e-11e9-820d-2e84e1ec0204.png)

**Comment by PierreRochard** [comment]
Yikes. It's likely a problem with the tls.cert tls.key files, I've added an error message so we can debug this in the next version.

If you want, try deleting the tls.key and tls.cert in ~/Library/Application Support/Lnd

Thanks for reporting the bug!

**Comment by jchello** [comment]
That did it! Thanks for the tip.

**Comment by PierreRochard** [comment]
Awesome! I'll automate that process to help future users
