### ISSUE TITLE
ZapDesktop 0.3.1

### ISSUE THREAD

**Issue by Jonbros01** [PierreRochard/node-launcher#80]
I just updated my ZapDesktop to V 0.3.1-beta.5049.
I have to create a new wallet in Zap.  
So I connect to my own node (by Node Launcher).  I copy the Host gRPC, TLS Cert Path and Macaroon Path to Zap connection details page.

But in Zap, in the Host field, it say it is unable to connect to host: Failed to connect before the deadline.

No sure exactly why.... before the update everything was working fine.

**Comment by PierreRochard** [comment]
Hmm odd, @mrfelton is there a timeout that was added with this version?

**Comment by Freefromchainz** [comment]
Kind of the same issue here I updated and zap is not accepting my password for lnd! I saw the update a few times today but ignored it, then i saw the issue JonBros was having and ignored it some more. but 5mins ago i gave it a shot anyway and this is the result!

**Comment by jchello** [comment]
@Jonbros01 @PierreRochard I encountered the same problem. Shut down LND and close Zap and restart them as you did before during setup. This solved it for me, at least.

**Comment by mrfelton** [comment]
Was the wallet that you are connecting to locked or unlocked? Was it already fully synced?

**Comment by Jonbros01** [comment]
Yes unlocked and fully sync.

That being said I tried to quit and relaunch Zap, LND and Bitcoin node... That didn't solved the issue.

I did restart my Mac and with the help of node- launcher launch Bitcoin / LND. And then at that moment ZapDesktop was then able to connect to the LND!!

So solution for me was a Mac restart!!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mrfelton** [comment]
@Jonbros01 and now it's working fine? You can disconnect, reconnect, log in and out etc without any further issues?

There are 2 issues that I'm aware of that are affecting things on mac a little, though I'm not really seeing any connection based on what you have described here:

1. [app not fully quitting  app quits fully on osx](https://github.com/LN-Zap/zap-desktop/pull/1160)
2. [ensure app notified on lnd disconnect](https://github.com/LN-Zap/zap-desktop/pull/1158)

The error "unable to connect to host: Failed to connect before the deadline." comes from grpc and indicates that it was not able to connect to your node. The usual cause of this is that your node is not actually running, or you are trying to connect to the wrong port.

**Comment by mrfelton** [comment]
> Hmm odd, @mrfelton is there a timeout that was added with this version?

The timeout has always been there @PierreRochard . We allow up to 20 seconds to establish a connection to the gRPC interface.
