### ISSUE TITLE
Remove quotes from config datadir

### ISSUE THREAD

**Issue by PierreRochard** [PierreRochard/node-launcher#82]

**Comment by BobleChinois** [comment]
Hi @PierreRochard , I just caught up on the conf you did yesterday with Justin and his students, this issue sounds easy to begin with, but not very self explanatory, can you give me a little more details to see if I can tackle this? Thanks!

**Comment by PierreRochard** [comment]
![image](https://user-images.githubusercontent.com/6299681/51186138-e0ffa980-18a6-11e9-88c8-5240e9a9f7ac.png)

**Comment by PierreRochard** [comment]
Actually, looks like I fixed this on master, thank you for taking a look @BobleChinois !
