### ISSUE TITLE
Alias not broadcasting properly 

### ISSUE THREAD

**Issue by Freefromchainz** [PierreRochard/node-launcher#83]
Hello pierre i updated zap yesterday and now the alias is not displaying properly.

Before update 
![node activity n alias](https://user-images.githubusercontent.com/8317700/50376206-52f61300-05c7-11e9-9b57-34b9e3adfaff.PNG)

after update
![node activity n alias after update](https://user-images.githubusercontent.com/8317700/50376202-4b366e80-05c7-11e9-9dbd-1f7e13bc3822.PNG)

LND.conf file 
# Auto-Generated Configuration File

# Node Launcher version 5.0.1

alias=MurexBitcoinSolutions
color=#800080

**Comment by PierreRochard** [comment]
Hi @Freefromchainz ! I'll have to forward you to https://github.com/LN-Zap/zap-desktop/issues as this is not directly related to the Node Launcher
