### ISSUE TITLE
Connecting to a known peer node

### ISSUE THREAD

**Issue by Freefromchainz** [PierreRochard/node-launcher#84]
We are attempting to connect to each other and open a channel! we are getting these errors!

When trying to connect to 03a3cef6d54b815a92502ae638fd50d602f986c959ecc582295fd456ca85daf125@
![connection failed with mstaples](https://user-images.githubusercontent.com/8317700/50385921-b309b980-069a-11e9-9340-28836358e8c0.PNG)

When trying to connect to 029b752bb30e868a9186e87d46d3c00f92da6c46741d210767a4b857186c395d9f@
![connection failed with mstaples 2](https://user-images.githubusercontent.com/8317700/50385944-0e3bac00-069b-11e9-91ad-46c261cef805.png)

**Comment by PierreRochard** [comment]
Port forwarding for 9735 must be enabled on your WiFi/Internet router, and your firewalls must be configured to accept connections on 9735

**Comment by PierreRochard** [comment]
No problem, happy to help!
