### ISSUE TITLE
App fails to run on MacOs 10.11

### ISSUE THREAD

**Issue by papadakn** [PierreRochard/node-launcher#99]
When trying to execute the App in my (old) Macbook Pro it closes immediately without any error message or GUI screen. Running on MacOs 10.11.6 due to hardware limitations.

Found a similar older issue that was reported here and according to this: https://pythonhosted.org/PyInstaller/usage.html#making-mac-os-x-apps-forward-compatible

you'd have to execute Pyinstaller on a 10.11 machine. Is there any chance you could that?

Regards,
Nikos

**Comment by PierreRochard** [comment]
Nope, sorry, 10.12 is the last version of macOS I'm supporting. You could manually run it in the command line with Python

**Comment by PierreRochard** [comment]
The reasons is simply that I don't have a computer with 10.11 installed, so if you want to send me one then that'd work!
